version: '3.3'

services:
  operatorDashboard:
    image: 127.0.0.1:5001/operator_dashboard
    build: src/
    volumes:
      - ./src/app/data/:/usr/src/app/data/
    ports:
      - "6789:6789"
    networks:
      - operatorNetwork
    restart: always

  redis:
    image: redis:alpine
    networks:
      - operatorNetwork
    restart: always

# Network
networks:
  operatorNetwork:

