version: '3.3'

services:
  operatorDashboard:
    image: 127.0.0.1:5001/operator_dashboard
    build:
      context: src/
      args:
        - LIBRDKAFKA_VERSION=$LIBRDKAFKA_VERSION
        - CONFLUENT_KAFKA_VERSION=$CONFLUENT_KAFKA_VERSION
    env_file:
      - .env
    volumes:
      - ./src/app/data/:/usr/src/app/data/
    ports:
      - "6789:6789"
    networks:
      - operatorNetwork
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "1"
          memory: 1G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s

  redis:
    image: redis:alpine
    networks:
      - operatorNetwork
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]

# Network
networks:
  operatorNetwork:

