version: '3.3'

services:
  operatorDashboard:
    image: 127.0.0.1:5001/operator_dashboard
    build:
      context: src/
      args:
        - LIBRDKAFKA_VERSION=$LIBRDKAFKA_VERSION
        - CONFLUENT_KAFKA_VERSION=$CONFLUENT_KAFKA_VERSION
    env_file:
      - .env
    volumes:
      - ./src/app/data/:/usr/src/app/data/
    ports:
      - "6789:6789"
    networks:
      - operatorNetwork
    restart: always

  redis:
    image: redis:alpine
    networks:
      - operatorNetwork
    restart: always

# Network
networks:
  operatorNetwork:

